server:
  port: 9001
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/javastudy?useUnicode=true&characterEncoding=utf8
    username: root
    password: k1234567
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  # 基于consul的服务配置
  cloud:
    consul: #consul相关配置
      host: 127.0.0.1 #ConsulServer请求地址 port: 8500 #ConsulServer端口
      port: 8500
      discovery:
        register: true  #是否注册
        instance-id: ${spring.application.name}-1 #实例ID(后面加个参数)
        service-name: ${spring.application.name} #服务实例名称
        port: ${server.port} #服务实例端口
        healthCheckPath: /actuator/health #健康检查路径
        healthCheckInterval: 15s #健康检查时间间隔
        prefer-ip-address: true #开启ip地址注册
        ip-address: ${spring.cloud.client.ip-address} #实例的请求ip
